name: build-test-and-deploy-app-student-one

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build --if-present
      - name: Test application
        run: npm run test --if-present


  security-test:
    needs:  unit-test
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js  ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build --if-present
      - name: Test application
        run:  npm audit fix --force

  deploy:
    if: github.ref == 'refs/heads/main'
    needs:  security-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.SERVICE_ID }}
          api_key: ${{ secrets.API_TOKEN }}
          wait_deploy: true
